#!/bin/bash
if ! docker info > /dev/null 2>&1; then
  echo "Please start docker and try again!"
  exit 1
fi

if [ "$1" = "build" ]; then
  docker-compose build
elif [ "$1" = "up" ]; then
  docker-compose up -d
elif [ "$1" = "down" ]; then
  docker-compose down
elif [ "$1" = "start" ]; then
  docker-compose start
elif [ "$1" = "stop" ]; then
  docker-compose stop
elif [ "$1" = "artisan" ]; then
  shift
  docker exec workspacer-api php artisan "$@"
elif [ "$1" = "composer" ]; then
  shift
  docker exec workspacer-api composer "$@"
elif [ "$1" = "npm" ]; then
  container=$2
  shift 2
  docker exec workspacer-$container npm "$@"
else
  echo "Command not found: $1"
  exit 1
fi

exit 0